coupans_manager/coupans/forms.py
from flask_wtf import FlaskForm
from wtforms import DateField, StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length


class CoupanForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(min=2, max=20)])
    code = StringField("Code", validators=[DataRequired(), Length(min=2, max=20)])
    platform_apply = StringField(
        "Applicable on platform", validators=[DataRequired(), Length(min=2, max=20)]
    )
    platform_get = StringField(
        "From where you got it", validators=[DataRequired(), Length(min=2, max=20)]
    )
    expiry_date = DateField("expiry", validators=[DataRequired()], format="%Y-%m-%d")
    details = TextAreaField("details", validators=[DataRequired()])
    submit = SubmitField("Add Coupan")

coupans_manager/main/routes.py
from flask import Blueprint, render_template, request

from coupans_manager.models import Coupan

main = Blueprint("main", __name__)


@main.route("/")
def index():
    return render_template("index.html")


@main.route("/coupans")
def show_coupans():
    page = request.args.get("page", 1, type=int)
    coupans_list = Coupan.query.order_by(Coupan.expiry_date).paginate(
        per_page=5, page=page
    )
    return render_template("coupans.html", coupans=coupans_list, title="ALL COUPANS")

coupans_manager/users/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from coupans_manager.users.utils import send_reset_email
from coupans_manager.models import Coupan, User

from coupans_manager.users.forms import (
    LoginForm,
    RegistrationForm,
    RequestResetForm,
    ResetPasswordForm,
    UpdateAccountForm,
)
from coupans_manager import bcrypt, db

users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form = RegistrationForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )

        user_1 = User(
            username=form.username.data, email=form.email.data, password=hashed_password
        )
        db.session.add(user_1)
        db.session.commit()

        flash(f"Your Account is created", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form = LoginForm()
    if form.validate_on_submit():
        user_1 = User.query.filter_by(email=form.email.data).first()

        if user_1 and bcrypt.check_password_hash(user_1.password, form.password.data):
            login_user(user_1, form.remember.data)
            next_page = request.args.get("next")
            return redirect(next_page) if next_page else redirect(url_for("main.index"))
        else:
            flash("Unsuccessful login attempt.Check details", "danger")

    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.index"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been  updated", "success")
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template("account.html", title="Account", form=form)


@users.route("/user/<string:username>")
def user_coupans(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    coupans_list = (
        Coupan.query.filter_by(author=user)
        .order_by(Coupan.expiry_date)
        .paginate(per_page=5, page=page)
    )
    return render_template(
        "user_coupans.html",
        coupans=coupans_list,
        title=f"{username} Coupans",
        user=user,
    )


@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("Email has been sent with instructions to reset password", "info")
        return redirect(url_for("users.login"))
    return render_template("reset_request.html", title="Reset Password", form=form)


@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    user = User.verify_reset_toekn(token)
    if user is None:
        flash("That is an invalid or ecpired token", "warning")
        return redirect(url_for("users.reset_request"))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )

        user.password = hashed_password
        db.session.commit()

        flash(f"Your Password has bee updated", "success")
        return redirect(url_for("users.login"))
    return render_template("reset_token.html", title="Reset Password", form=form)

coupans_manager/templates/account.html
{% extends "layout.html" %}
{% block content %}
<div class="card">
    <div class="card-body">
        <h5 class="card-title">User Details
        </h5>
        <p class="card-text"><b>Username</b> {{current_user.email}}.</p>
        <p class="card-text"><b>Email</b> {{current_user.email}}.</p>

    </div>
</div>

<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}

        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Account Info</legend>
            <div class="form-group">
                {{form.username.label(class="form-control-label")}} {% if
                form.username.errors %} {{form.username(class="form-control
                form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>

                {% else %} {{form.username(class="form-control form-control-lg")}} {%
                endif %}
            </div>
            <div class="form-group">
                {{form.email.label(class="form-control-label")}}
                {% if form.email.errors %} {{form.email(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>

                {% else %} {{form.email(class="form-control form-control-lg")}} {% endif
                %}
            </div>
        </fieldset>
        <div class="form-group">{{form.submit(class="btn btn-primary")}}</div>
    </form>
</div>
{% endblock content %}

coupans_manager/templates/coupan.html
{% extends "layout.html "%} {% block content %}
<h1>All Coupans</h1>

<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{coupan.title}}</h5>
        <h6 class="card-subtitle mb-2 text-muted"><a
                href="{{url_for('users.user_coupans',username=coupan.author.username)}}">By
                {{coupan.author.username}}</a></h6>
        <p class="card-text"><b>Coupan Code:</b> {{coupan.code}}</p>
        <p class="card-text"><b>Platform To Apply:</b> {{coupan.platform_apply}}</p>
        <p class="card-text"><b>
                Platform We got from:</b> {{coupan.platform_get}}
        </p>
        <p class="card-text"><b>Expiry Date:</b> {{coupan.expiry_date.strftime('%d-%b-%Y')}}</p>
        <p class="card-text"><b>COupan Details:</b> {{coupan.details}}</p>
        <p class="card-text"><b>Is expired:</b> {{coupan.is_expired}}</p>
        {% if coupan.author == current_user %}
        <a href="{{url_for('coupans.update_coupan',coupan_id=coupan.id)}}" class="btn btn-primary">Update</a>
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">
            Delete
        </button>
        {% endif %}
    </div>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">You sure you want to delete Coupan</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <form action="{{url_for('coupans.delete_coupan',coupan_id=coupan.id)}}" method="POST">
                        <input type="submit" class="btn btn-danger" value="Delete">

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

coupans_manager/templates/create_coupan.html
{% extends "layout.html" %}
{% block content %}
<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}

        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{legend}}</legend>
            <div class="form-group">
                {{form.title.label(class="form-control-label")}} {% if form.title.errors
                %} {{form.email(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>

                {% else %} {{form.title(class="form-control form-control-lg")}} {% endif
                %}
            </div>
            <div class="form-group">
                {{form.code.label(class="form-control-label")}} {% if
                form.code.errors %} {{form.code(class="form-control
                form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.code.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>

                {% else %} {{form.code(class="form-control form-control-lg")}} {%
                endif %}
            </div>

            <div class="form-group">
                {{form.platform_apply.label(class="form-control-label")}} {% if form.platform_apply.errors
                %} {{form.platform_apply(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.platform_apply.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>

                {% else %} {{form.platform_apply(class="form-control form-control-lg")}} {% endif
                %}

                <div class="form-group">
                    {{form.platform_get.label(class="form-control-label")}} {% if
                    form.platform_get.errors %} {{form.platform_get(class="form-control
                    form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.platform_get.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </div>

                    {% else %} {{form.platform_get(class="form-control form-control-lg")}} {%
                    endif %}
                </div>

                <div class="form-group">
                    {{form.expiry_date.label(class="form-control-label")}} {% if form.expiry_date.errors
                    %} {{form.email(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.expiry_date.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </div>

                    {% else %} {{form.expiry_date(class="form-control form-control-lg")}} {% endif
                    %}

                    <div class="form-group">
                        {{form.details.label(class="form-control-label")}} {% if
                        form.details.errors %} {{form.details(class="form-control
                        form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.details.errors %}
                            <span>{{error}}</span>
                            {% endfor %}
                        </div>

                        {% else %} {{form.details(class="form-control form-control-lg")}} {%
                        endif %}
                    </div>

        </fieldset>
        <div class="form-group">{{form.submit(class="btn btn-primary")}}</div>
    </form>
</div>

{% endblock content %}

coupans_manager/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />

  {% if title %}
  <title>{{title}}</title>
  {% else %}
  <title>Coupan Management</title>
  {% endif %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid"></div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{url_for('main.index')}}">Home</a>
        </li>
        <li>
          <a class="nav-link active" aria-current="page" href="{{url_for('main.show_coupans')}}">Coupans</a>
        </li>
      </ul>
      <a class="nav-link active" aria-current="page" href="{{url_for('coupans.new_coupan')}}">Add Coupan</a>
      {% if current_user.is_authenticated %}
      <a class="nav-link active" aria-current="page" href="{{url_for('users.logout')}}">Logout</a>
      <a class="nav-link active" aria-current="page" href="{{url_for('users.account')}}">Account {{current_user.username}}</a>
      {% else %}
      <a class="nav-link active" aria-current="page" href="{{url_for('users.login')}}">Login</a>
      <a class="nav-link active" aria-current="page" href="{{url_for('users.register')}}">Register</a>
      {% endif %}
    </div>
  </nav>
  <div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <ul class="flashes">
      {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
      {% endfor %}
    </ul>
    {% endif %} {% endwith %} {% block content %} {% endblock %}
  </div>
  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
</body>

</html>