coupons_manager/coupons/forms.py
from flask_wtf import FlaskForm
from wtforms import DateField, StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length


class CouponForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(min=2, max=20)])
    code = StringField("Code", validators=[DataRequired(), Length(min=2, max=20)])
    platform_apply = StringField(
        "Applicable on platform", validators=[DataRequired(), Length(min=2, max=20)]
    )
    platform_get = StringField(
        "From where you got it", validators=[DataRequired(), Length(min=2, max=20)]
    )
    expiry_date = DateField("expiry", validators=[DataRequired()], format="%Y-%m-%d")
    details = TextAreaField("details", validators=[DataRequired()])
    submit = SubmitField("Add Coupon")

coupons_manager/coupons/routes.py
from datetime import datetime
from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from coupons_manager.coupons.forms import CouponForm
from coupons_manager.models import Coupon
from coupons_manager import db

coupons = Blueprint("coupons", __name__)


@coupons.route("/coupon/new", methods=["GET", "POST"])
@login_required
def new_coupon():
    form = CouponForm()
    if form.validate_on_submit():
        coupon_1 = Coupon(
            title=form.title.data,
            code=form.code.data,
            platform_apply=form.platform_apply.data,
            platform_get=form.platform_get.data,
            expiry_date=form.expiry_date.data,
            details=form.details.data,
            author=current_user,
        )
        db.session.add(coupon_1)
        db.session.commit()

        flash("New Coupon Added", "success")
        return redirect(url_for("main.show_coupons"))

    return render_template(
        "create_coupon.html", title="New Coupon", form=form, legend="Create Coupan"
    )


@coupons.route("/coupon/<int:coupon_id>")
def coupon(coupon_id):
    coupon_1 = Coupon.query.get_or_404(coupon_id)
    return render_template(
        "coupon.html",
        title=coupon_1.title,
        coupon=coupon_1,
    )


@coupons.route("/coupon/<int:coupon_id>/update", methods=["GET", "POST"])
@login_required
def update_coupon(coupon_id):
    coupon_1 = Coupon.query.get_or_404(coupon_id)
    if coupon_1.author != current_user:
        abort(403)
    form = CouponForm()

    if form.validate_on_submit():
        coupon_1.title = form.title.data
        coupon_1.code = form.code.data
        coupon_1.platform_apply = form.platform_apply.data
        coupon_1.platform_get = form.platform_get.data
        coupon_1.details = form.details.data
        coupon_1.date_posted = datetime.utcnow()
        db.session.commit()
        flash("Coupons details Updated", "success")
        return redirect(url_for("coupons.coupon", coupon_id=coupon_1.id))
    elif request.method == "GET":
        form.title.data = coupon_1.title
        form.code.data = coupon_1.code
        form.platform_apply.data = coupon_1.platform_apply
        form.platform_get.data = coupon_1.platform_get
        form.expiry_date.data = coupon_1.expiry_date
        form.details.data = coupon_1.details

    return render_template(
        "create_coupon.html", title="Update Coupon", form=form, legend="Update COupan"
    )


@coupons.route("/coupon/<int:coupon_id>/delete", methods=["POST"])
@login_required
def delete_coupon(coupon_id):
    coupon_1 = Coupon.query.get_or_404(coupon_id)
    if coupon_1.author != current_user:
        abort(403)
    db.session.delete(coupon_1)
    db.session.commit()
    flash("Coupon Deleted", "success")
    return redirect(url_for("main.show_coupons"))

coupons_manager/main/routes.py
from flask import Blueprint, render_template, request

from coupons_manager.models import Coupon

main = Blueprint("main", __name__)


@main.route("/")
def index():
    return render_template("index.html")


@main.route("/coupons")
def show_coupons():
    page = request.args.get("page", 1, type=int)
    coupons_list = Coupon.query.order_by(Coupon.expiry_date).paginate(
        per_page=5, page=page
    )
    return render_template("coupons.html", coupons=coupons_list, title="ALL COUPANS")

coupons_manager/users/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from coupons_manager.users.utils import send_reset_email
from coupons_manager.models import Coupon, User

from coupons_manager.users.forms import (
    LoginForm,
    RegistrationForm,
    RequestResetForm,
    ResetPasswordForm,
    UpdateAccountForm,
)
from coupons_manager import bcrypt, db

users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form = RegistrationForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )

        user_1 = User(
            username=form.username.data, email=form.email.data, password=hashed_password
        )
        db.session.add(user_1)
        db.session.commit()

        flash(f"Your Account is created", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form = LoginForm()
    if form.validate_on_submit():
        user_1 = User.query.filter_by(email=form.email.data).first()

        if user_1 and bcrypt.check_password_hash(user_1.password, form.password.data):
            login_user(user_1, form.remember.data)
            next_page = request.args.get("next")
            return redirect(next_page) if next_page else redirect(url_for("main.index"))
        else:
            flash("Unsuccessful login attempt.Check details", "danger")

    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.index"))


@login_required
@users.route("/user/delete", methods=["POST"])
def delete_account():
    Coupon.query.filter_by(user_id=current_user.id).delete()
    db.session.delete(current_user)
    db.session.commit()
    logout_user()
    flash("Account Deletion Successfull", "success")
    return redirect(url_for("main.index"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been  updated", "success")
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template("account.html", title="Account", form=form)


@users.route("/user/<string:username>")
def user_coupons(username):
    page = request.args.get("page", 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    coupons_list = (
        Coupon.query.filter_by(author=user)
        .order_by(Coupon.expiry_date)
        .paginate(per_page=5, page=page)
    )
    return render_template(
        "user_coupons.html",
        coupons=coupons_list,
        title=f"{username} Coupons",
        user=user,
    )


@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("Email has been sent with instructions to reset password", "info")
        return redirect(url_for("users.login"))
    return render_template("reset_request.html", title="Reset Password", form=form)


@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    user = User.verify_reset_toekn(token)
    if user is None:
        flash("That is an invalid or ecpired token", "warning")
        return redirect(url_for("users.reset_request"))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )

        user.password = hashed_password
        db.session.commit()

        flash(f"Your Password has bee updated", "success")
        return redirect(url_for("users.login"))
    return render_template("reset_token.html", title="Reset Password", form=form)

coupons_manager/templates/account.html
{% extends "layout.html" %}
{% block content %}
<div class="card">
    <div class="card-body">
        <h5 class="card-title">User Details
        </h5>
        <p class="card-text"><b>Username</b> {{current_user.username}}</p>
        <p class="card-text"><b>Email</b> {{current_user.email}}</p>

        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">
            Delete Account
        </button>
    </div>
</div>

<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}

        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Account Info</legend>
            <div class="form-group">
                {{form.username.label(class="form-control-label")}} {% if
                form.username.errors %} {{form.username(class="form-control
                form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>

                {% else %} {{form.username(class="form-control form-control-lg")}} {%
                endif %}
            </div>
            <div class="form-group">
                {{form.email.label(class="form-control-label")}}
                {% if form.email.errors %} {{form.email(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>

                {% else %} {{form.email(class="form-control form-control-lg")}} {% endif
                %}
            </div>
        </fieldset>
        <div class="form-group">{{form.submit(class="btn btn-primary")}}</div>
    </form>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">You sure you want to delete account. All associated coupons will also
                    get deleted</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form action="{{url_for('users.delete_account')}}" method="POST">
                    <input type="submit" class="btn btn-danger" value="Delete">

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

coupons_manager/templates/coupon.html
{% extends "layout.html "%}
{% block content %}
<h1>All Coupons</h1>

<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{coupon.title}}</h5>
        <h6 class="card-subtitle mb-2 text-muted"><a
                href="{{url_for('users.user_coupons',username=coupon.author.username)}}">By
                {{coupon.author.username}}</a></h6>
        <p class="card-text"><b>Coupon Code:</b> {{coupon.code}}</p>
        <p class="card-text"><b>Platform To Apply:</b> {{coupon.platform_apply}}</p>
        <p class="card-text"><b>
                Platform We got from:</b> {{coupon.platform_get}}
        </p>
        <p class="card-text"><b>Expiry Date:</b> {{coupon.expiry_date.strftime('%d-%b-%Y')}}</p>
        <p class="card-text"><b>COupan Details:</b> {{coupon.details}}</p>
        <p class="card-text"><b>Is expired:</b> {{coupon.is_expired}}</p>
        {% if coupon.author == current_user %}
        <a href="{{url_for('coupons.update_coupon',coupon_id=coupon.id)}}" class="btn btn-primary">Update</a>
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">
            Delete
        </button>
        {% endif %}
    </div>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">You sure you want to delete Coupon</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <form action="{{url_for('coupons.delete_coupon',coupon_id=coupon.id)}}" method="POST">
                        <input type="submit" class="btn btn-danger" value="Delete">

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

coupons_manager/templates/coupons.html
{% extends "layout.html "%}
{% block content %}
<h1>All Coupans</h1>
{% for coupon in coupons.items %}
<div class="card mb-1">
  <div class="card-body">
    <h5 class="card-title">
      <a class="link-primary" href="{{url_for('coupons.coupon',coupon_id=coupon.id)}}">{{coupon.title}}</a>
    </h5>
    <h6 class="card-subtitle mb-2 text-muted"><a
        href="{{url_for('users.user_coupons',username=coupon.author.username)}}">By
        {{coupon.author.username}}</a></h6>
    <p class="card-text"><b>Coupan Code:</b> {{coupon.code}}</p>
    <p class="card-text"><b>Platform To Apply:</b> {{coupon.platform_apply}}</p>
    <p class="card-text"><b>
        Platform We got from:</b> {{coupon.platform_get}}
    </p>
    <p class="card-text"><b>Expiry Date:</b> {{coupon.expiry_date.strftime('%d-%b-%Y')}}</p>
    <p class="card-text"><b>COupan Details:</b> {{coupon.details}}</p>
    <p class="card-text"><b>Is expired:</b> {{coupon.is_expired}}</p>
  </div>
</div>

{% endfor %}
{% for page_num in coupons.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
{% if page_num %}
{% if coupons.page == page_num %}
<a class="btn btn-info mb-4" href="{{url_for('main.show_coupons',page=page_num)}}">{{page_num}}</a>
{% else %}
<a class="btn btn-outline-info mb-4" href="{{url_for('main.show_coupons',page=page_num)}}">{{page_num}}</a>
{% endif %}
{% else %}
...
{% endif %}
{% endfor %}
{% endblock content %}

coupons_manager/templates/create_coupon.html
{% extends "layout.html" %}
{% block content %}
<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}

        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{legend}}</legend>
            <div class="form-group">
                {{form.title.label(class="form-control-label")}} {% if form.title.errors
                %} {{form.email(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>

                {% else %} {{form.title(class="form-control form-control-lg")}} {% endif
                %}
            </div>
            <div class="form-group">
                {{form.code.label(class="form-control-label")}} {% if
                form.code.errors %} {{form.code(class="form-control
                form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.code.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>

                {% else %} {{form.code(class="form-control form-control-lg")}} {%
                endif %}
            </div>

            <div class="form-group">
                {{form.platform_apply.label(class="form-control-label")}} {% if form.platform_apply.errors
                %} {{form.platform_apply(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.platform_apply.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>

                {% else %} {{form.platform_apply(class="form-control form-control-lg")}} {% endif
                %}

                <div class="form-group">
                    {{form.platform_get.label(class="form-control-label")}} {% if
                    form.platform_get.errors %} {{form.platform_get(class="form-control
                    form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.platform_get.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </div>

                    {% else %} {{form.platform_get(class="form-control form-control-lg")}} {%
                    endif %}
                </div>

                <div class="form-group">
                    {{form.expiry_date.label(class="form-control-label")}} {% if form.expiry_date.errors
                    %} {{form.email(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.expiry_date.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                    </div>

                    {% else %} {{form.expiry_date(class="form-control form-control-lg")}} {% endif
                    %}

                    <div class="form-group">
                        {{form.details.label(class="form-control-label")}} {% if
                        form.details.errors %} {{form.details(class="form-control
                        form-control-lg is-invalid")}}
                        <div class="invalid-feedback">
                            {% for error in form.details.errors %}
                            <span>{{error}}</span>
                            {% endfor %}
                        </div>

                        {% else %} {{form.details(class="form-control form-control-lg")}} {%
                        endif %}
                    </div>

        </fieldset>
        <div class="form-group">{{form.submit(class="btn btn-primary")}}</div>
    </form>
</div>

{% endblock content %}

coupons_manager/templates/index.html
{% extends "layout.html" %} {% block content %}
<h1>Coupon Management system</h1>

{% endblock content %}

coupons_manager/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />

  {% if title %}
  <title>{{title}}</title>
  {% else %}
  <title>Coupon Management</title>
  {% endif %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid"></div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <a class="nav-link active" aria-current="page" href="{{url_for('main.index')}}">Home</a>
      <a class="nav-link active" aria-current="page" href="{{url_for('main.show_coupons')}}">Coupons</a>
      <a class="nav-link active" aria-current="page" href="{{url_for('coupons.new_coupon')}}">Add Coupon</a>
      {% if current_user.is_authenticated %}
      <a class="nav-link active" aria-current="page" href="{{url_for('users.logout')}}">Logout</a>
      <a class="nav-link active" aria-current="page" href="{{url_for('users.account')}}">Account
        {{current_user.username}}</a>
      {% else %}
      <a class="nav-link active" aria-current="page" href="{{url_for('users.login')}}">Login</a>
      <a class="nav-link active" aria-current="page" href="{{url_for('users.register')}}">Register</a>
      {% endif %}
    </div>
  </nav>
  <div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <ul class="flashes">
      {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
      {% endfor %}
    </ul>
    {% endif %} {% endwith %} {% block content %} {% endblock %}
  </div>
  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
</body>

</html>

coupons_manager/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div>
  <form method="POST" action="">
    {{ form.hidden_tag() }}

    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Login</legend>
      <div class="form-group">
        {{form.email.label(class="form-control-label")}} {% if form.email.errors
        %} {{form.email(class="form-control form-control-lg is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>

        {% else %} {{form.email(class="form-control form-control-lg")}} {% endif
        %}
      </div>
      <div class="form-group">
        {{form.password.label(class="form-control-label")}} {% if
        form.password.errors %} {{form.password(class="form-control
        form-control-lg is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>

        {% else %} {{form.password(class="form-control form-control-lg")}} {%
        endif %}
      </div>
      <div class="form-check">
        {{form.remember(class="form-check-input")}}
        {{form.remember.label(class="form-check-label")}}
      </div>
    </fieldset>
    <div class="form-group">{{form.submit(class="btn btn-primary")}}</div>
    <small class="text-muted ml-2">
      <a href="{{url_for('users.reset_request')}}">Forgot Password?</a>
    </small>
  </form>
</div>
<div class="border-top pt-3">
  <small class="text-muted">
    Don't have an coount?
    <a class="ml-2" href="{{url_for('users.register')}}">Sign Up Now</a>
  </small>
</div>

{% endblock content %}

coupons_manager/templates/register.html
{% extends "layout.html" %}
{% block content %}
<div>
  <form method="POST" action="">
    {{ form.hidden_tag() }}

    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Registration</legend>
      <div class="form-group">
        {{form.username.label(class="form-control-label")}} {% if
        form.username.errors %} {{form.username(class="form-control
        form-control-lg is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.username.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>

        {% else %} {{form.username(class="form-control form-control-lg")}} {%
        endif %}
      </div>
      <div class="form-group">
        {{form.email.label(class="form-control-label")}} {% if form.email.errors
        %} {{form.email(class="form-control form-control-lg is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>

        {% else %} {{form.email(class="form-control form-control-lg")}} {% endif
        %}
      </div>
      <div class="form-group">
        {{form.password.label(class="form-control-label")}} {% if
        form.password.errors %} {{form.password(class="form-control
        form-control-lg is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>

        {% else %} {{form.password(class="form-control form-control-lg")}} {%
        endif %}
      </div>
      <div class="form-group">
        {{form.confirm_password.label(class="form-control-label")}} {% if
        form.confirm_password.errors %}
        {{form.confirm_password(class="form-control form-control-lg
        is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.confirm_password.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>

        {% else %} {{form.confirm_password(class="form-control
        form-control-lg")}} {% endif %}
      </div>
    </fieldset>
    <div class="form-group">{{form.submit(class="btn btn-primary")}}</div>
  </form>
</div>
<div class="border-top pt-3">
  <small class="text-muted">
    Already have an account?
    <a class="ml-2" href="{{url_for('users.login')}}">Sign In</a>
  </small>
</div>

{% endblock content %}

coupons_manager/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            <div class="form-group">
                {{form.email.label(class="form-control-label")}} {% if form.email.errors
                %} {{form.email(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>

                {% else %} {{form.email(class="form-control form-control-lg")}} {% endif
                %}
            </div>
        </fieldset>
        <div class="form-group">{{form.submit(class="btn btn-primary")}}</div>
    </form>
</div>
{% endblock content %}

coupons_manager/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            <div class="form-group">
                {{form.password.label(class="form-control-label")}} {% if form.password.errors
                %} {{form.password(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>

                {% else %} {{form.password(class="form-control form-control-lg")}} {% endif
                %}
            </div>
            <div class="form-group">
                {{form.confirm_password.label(class="form-control-label")}} {% if form.confirm_password.errors
                %} {{form.confirm_password(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>

                {% else %} {{form.confirm_password(class="form-control form-control-lg")}} {% endif
                %}
            </div>

        </fieldset>
        <div class="form-group">{{form.submit(class="btn btn-primary")}}</div>
    </form>
</div>
{% endblock content %}

coupons_manager/templates/user_coupons.html
{% extends "layout.html "%}
{% block content %}
<h1 class="mb-3">Coupons by {{user.username}} {{coupons.total}}</h1>
{% for coupon in coupons.items %}
<div class="card mb-1">
    <div class="card-body">
        <h5 class="card-title">
            <a class="link-primary" href="{{url_for('coupons.coupon',coupon_id=coupon.id)}}">{{coupon.title}}</a>
        </h5>
        <h6 class="card-subtitle mb-2 text-muted"><a
                href="{{url_for('users.user_coupons',username=coupon.author.username)}}">By
                {{coupon.author.username}}</a></h6>
        <p class="card-text"><b>Coupon Code:</b> {{coupon.code}}</p>
        <p class="card-text"><b>Platform To Apply:</b> {{coupon.platform_apply}}</p>
        <p class="card-text"><b>
                Platform We got from:</b> {{coupon.platform_get}}
        </p>
        <p class="card-text"><b>Expiry Date:</b> {{coupon.expiry_date.strftime('%d-%b-%Y')}}</p>
        <p class="card-text"><b>COupan Details:</b> {{coupon.details}}</p>
        <p class="card-text"><b>Is expired:</b> {{coupon.is_expired}}</p>
    </div>
</div>

{% endfor %}
{% for page_num in coupons.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
{% if page_num %}
{% if coupons.page == page_num %}
<a class="btn btn-info mb-4"
    href="{{url_for('users.user_coupons',username=user.username,page=page_num)}}">{{page_num}}</a>
{% else %}
<a class="btn btn-outline-info mb-4"
    href="{{url_for('users.user_coupons',username=user.username,page=page_num)}}">{{page_num}}</a>
{% endif %}
{% else %}
...
{% endif %}
{% endfor %}
{% endblock content %}